// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dombyte/datalogger/internal/datasource"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWriter creates a new instance of MockWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWriter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}

type MockWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWriter) EXPECT() *MockWriter_Expecter {
	return &MockWriter_Expecter{mock: &_m.Mock}
}

// Name provides a mock function for the type MockWriter
func (_mock *MockWriter) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockWriter_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockWriter_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockWriter_Expecter) Name() *MockWriter_Name_Call {
	return &MockWriter_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockWriter_Name_Call) Run(run func()) *MockWriter_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWriter_Name_Call) Return(s string) *MockWriter_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockWriter_Name_Call) RunAndReturn(run func() string) *MockWriter_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockWriter
func (_mock *MockWriter) Start(ctx context.Context, input <-chan datasource.DataPoint) <-chan error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 <-chan error
	if returnFunc, ok := ret.Get(0).(func(context.Context, <-chan datasource.DataPoint) <-chan error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan error)
		}
	}
	return r0
}

// MockWriter_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockWriter_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - input <-chan datasource.DataPoint
func (_e *MockWriter_Expecter) Start(ctx any, input any) *MockWriter_Start_Call {
	return &MockWriter_Start_Call{Call: _e.mock.On("Start", ctx, input)}
}

func (_c *MockWriter_Start_Call) Run(run func(ctx context.Context, input <-chan datasource.DataPoint)) *MockWriter_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 <-chan datasource.DataPoint
		if args[1] != nil {
			arg1 = args[1].(<-chan datasource.DataPoint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWriter_Start_Call) Return(errCh <-chan error) *MockWriter_Start_Call {
	_c.Call.Return(errCh)
	return _c
}

func (_c *MockWriter_Start_Call) RunAndReturn(run func(ctx context.Context, input <-chan datasource.DataPoint) <-chan error) *MockWriter_Start_Call {
	_c.Call.Return(run)
	return _c
}
