// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	datasource "github.com/dombyte/datalogger/internal/datasource"
	mock "github.com/stretchr/testify/mock"
)

// Writer is an autogenerated mock type for the Writer type
type Writer struct {
	mock.Mock
}

type Writer_Expecter struct {
	mock *mock.Mock
}

func (_m *Writer) EXPECT() *Writer_Expecter {
	return &Writer_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with no fields
func (_m *Writer) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Writer_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Writer_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Writer_Expecter) Name() *Writer_Name_Call {
	return &Writer_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Writer_Name_Call) Run(run func()) *Writer_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Writer_Name_Call) Return(_a0 string) *Writer_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Writer_Name_Call) RunAndReturn(run func() string) *Writer_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx, input
func (_m *Writer) Start(ctx context.Context, input <-chan datasource.DataPoint) <-chan error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 <-chan error
	if rf, ok := ret.Get(0).(func(context.Context, <-chan datasource.DataPoint) <-chan error); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan error)
		}
	}

	return r0
}

// Writer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Writer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - input <-chan datasource.DataPoint
func (_e *Writer_Expecter) Start(ctx interface{}, input interface{}) *Writer_Start_Call {
	return &Writer_Start_Call{Call: _e.mock.On("Start", ctx, input)}
}

func (_c *Writer_Start_Call) Run(run func(ctx context.Context, input <-chan datasource.DataPoint)) *Writer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(<-chan datasource.DataPoint))
	})
	return _c
}

func (_c *Writer_Start_Call) Return(_a0 <-chan error) *Writer_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Writer_Start_Call) RunAndReturn(run func(context.Context, <-chan datasource.DataPoint) <-chan error) *Writer_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewWriter creates a new instance of Writer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Writer {
	mock := &Writer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
