---
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - TZ=Europe/Berlin
    command: -config=/app/config.yaml
    restart: unless-stopped
