// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	datasource "github.com/dombyte/datalogger/internal/datasource"
	mock "github.com/stretchr/testify/mock"
)

// DeviceReader is an autogenerated mock type for the DeviceReader type
type DeviceReader struct {
	mock.Mock
}

type DeviceReader_Expecter struct {
	mock *mock.Mock
}

func (_m *DeviceReader) EXPECT() *DeviceReader_Expecter {
	return &DeviceReader_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with no fields
func (_m *DeviceReader) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// DeviceReader_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type DeviceReader_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *DeviceReader_Expecter) Name() *DeviceReader_Name_Call {
	return &DeviceReader_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *DeviceReader_Name_Call) Run(run func()) *DeviceReader_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DeviceReader_Name_Call) Return(_a0 string) *DeviceReader_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeviceReader_Name_Call) RunAndReturn(run func() string) *DeviceReader_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *DeviceReader) Start(ctx context.Context) <-chan datasource.DataPoint {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 <-chan datasource.DataPoint
	if rf, ok := ret.Get(0).(func(context.Context) <-chan datasource.DataPoint); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan datasource.DataPoint)
		}
	}

	return r0
}

// DeviceReader_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type DeviceReader_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DeviceReader_Expecter) Start(ctx interface{}) *DeviceReader_Start_Call {
	return &DeviceReader_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *DeviceReader_Start_Call) Run(run func(ctx context.Context)) *DeviceReader_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *DeviceReader_Start_Call) Return(_a0 <-chan datasource.DataPoint) *DeviceReader_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeviceReader_Start_Call) RunAndReturn(run func(context.Context) <-chan datasource.DataPoint) *DeviceReader_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeviceReader creates a new instance of DeviceReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeviceReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeviceReader {
	mock := &DeviceReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
