// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dombyte/datalogger/internal/datasource"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeviceReader creates a new instance of MockDeviceReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceReader {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockDeviceReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockDeviceReader is an autogenerated mock type for the DeviceReader type
type MockDeviceReader struct {
	mock.Mock
}

type MockDeviceReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceReader) EXPECT() *MockDeviceReader_Expecter {
	return &MockDeviceReader_Expecter{mock: &_m.Mock}
}

// Name provides a mock function for the type MockDeviceReader
func (_mock *MockDeviceReader) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDeviceReader_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockDeviceReader_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockDeviceReader_Expecter) Name() *MockDeviceReader_Name_Call {
	return &MockDeviceReader_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockDeviceReader_Name_Call) Run(run func()) *MockDeviceReader_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceReader_Name_Call) Return(s string) *MockDeviceReader_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDeviceReader_Name_Call) RunAndReturn(run func() string) *MockDeviceReader_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockDeviceReader
func (_mock *MockDeviceReader) Start(ctx context.Context) <-chan []datasource.DataPoint {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 <-chan []datasource.DataPoint
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan []datasource.DataPoint); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan []datasource.DataPoint)
		}
	}
	return r0
}

// MockDeviceReader_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockDeviceReader_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDeviceReader_Expecter) Start(ctx any) *MockDeviceReader_Start_Call {
	return &MockDeviceReader_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockDeviceReader_Start_Call) Run(run func(ctx context.Context)) *MockDeviceReader_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeviceReader_Start_Call) Return(dataPointsCh <-chan []datasource.DataPoint) *MockDeviceReader_Start_Call {
	_c.Call.Return(dataPointsCh)
	return _c
}

func (_c *MockDeviceReader_Start_Call) RunAndReturn(run func(ctx context.Context) <-chan []datasource.DataPoint) *MockDeviceReader_Start_Call {
	_c.Call.Return(run)
	return _c
}
