// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	nethttp "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// CloseIdleConnections provides a mock function with no fields
func (_m *Client) CloseIdleConnections() {
	_m.Called()
}

// Client_CloseIdleConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseIdleConnections'
type Client_CloseIdleConnections_Call struct {
	*mock.Call
}

// CloseIdleConnections is a helper method to define mock.On call
func (_e *Client_Expecter) CloseIdleConnections() *Client_CloseIdleConnections_Call {
	return &Client_CloseIdleConnections_Call{Call: _e.mock.On("CloseIdleConnections")}
}

func (_c *Client_CloseIdleConnections_Call) Run(run func()) *Client_CloseIdleConnections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_CloseIdleConnections_Call) Return() *Client_CloseIdleConnections_Call {
	_c.Call.Return()
	return _c
}

func (_c *Client_CloseIdleConnections_Call) RunAndReturn(run func()) *Client_CloseIdleConnections_Call {
	_c.Run(run)
	return _c
}

// Do provides a mock function with given fields: req
func (_m *Client) Do(req *nethttp.Request) (*nethttp.Response, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *nethttp.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*nethttp.Request) (*nethttp.Response, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*nethttp.Request) *nethttp.Response); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nethttp.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*nethttp.Request) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type Client_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - req *nethttp.Request
func (_e *Client_Expecter) Do(req interface{}) *Client_Do_Call {
	return &Client_Do_Call{Call: _e.mock.On("Do", req)}
}

func (_c *Client_Do_Call) Run(run func(req *nethttp.Request)) *Client_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*nethttp.Request))
	})
	return _c
}

func (_c *Client_Do_Call) Return(_a0 *nethttp.Response, _a1 error) *Client_Do_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_Do_Call) RunAndReturn(run func(*nethttp.Request) (*nethttp.Response, error)) *Client_Do_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
