// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	influxdb3 "github.com/InfluxCommunity/influxdb3-go/v2/influxdb3"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *Client) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Client_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Client_Expecter) Close() *Client_Close_Call {
	return &Client_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Client_Close_Call) Run(run func()) *Client_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Close_Call) Return(_a0 error) *Client_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_Close_Call) RunAndReturn(run func() error) *Client_Close_Call {
	_c.Call.Return(run)
	return _c
}

// WritePoints provides a mock function with given fields: ctx, points, opts
func (_m *Client) WritePoints(ctx context.Context, points []*influxdb3.Point, opts ...influxdb3.WriteOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, points)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WritePoints")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*influxdb3.Point, ...influxdb3.WriteOption) error); ok {
		r0 = rf(ctx, points, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_WritePoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WritePoints'
type Client_WritePoints_Call struct {
	*mock.Call
}

// WritePoints is a helper method to define mock.On call
//   - ctx context.Context
//   - points []*influxdb3.Point
//   - opts ...influxdb3.WriteOption
func (_e *Client_Expecter) WritePoints(ctx interface{}, points interface{}, opts ...interface{}) *Client_WritePoints_Call {
	return &Client_WritePoints_Call{Call: _e.mock.On("WritePoints",
		append([]interface{}{ctx, points}, opts...)...)}
}

func (_c *Client_WritePoints_Call) Run(run func(ctx context.Context, points []*influxdb3.Point, opts ...influxdb3.WriteOption)) *Client_WritePoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]influxdb3.WriteOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(influxdb3.WriteOption)
			}
		}
		run(args[0].(context.Context), args[1].([]*influxdb3.Point), variadicArgs...)
	})
	return _c
}

func (_c *Client_WritePoints_Call) Return(_a0 error) *Client_WritePoints_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_WritePoints_Call) RunAndReturn(run func(context.Context, []*influxdb3.Point, ...influxdb3.WriteOption) error) *Client_WritePoints_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
