// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/InfluxCommunity/influxdb3-go/v2/influxdb3"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockClient
func (_mock *MockClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(err error) *MockClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// WritePoints provides a mock function for the type MockClient
func (_mock *MockClient) WritePoints(ctx context.Context, points []*influxdb3.Point, opts ...influxdb3.WriteOption) error {
	// influxdb3.WriteOption
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, points)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WritePoints")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*influxdb3.Point, ...influxdb3.WriteOption) error); ok {
		r0 = returnFunc(ctx, points, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_WritePoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WritePoints'
type MockClient_WritePoints_Call struct {
	*mock.Call
}

// WritePoints is a helper method to define mock.On call
//   - ctx context.Context
//   - points []*influxdb3.Point
//   - opts ...influxdb3.WriteOption
func (_e *MockClient_Expecter) WritePoints(ctx any, points any, opts ...any) *MockClient_WritePoints_Call {
	return &MockClient_WritePoints_Call{Call: _e.mock.On("WritePoints",
		append([]any{ctx, points}, opts...)...)}
}

func (_c *MockClient_WritePoints_Call) Run(run func(ctx context.Context, points []*influxdb3.Point, opts ...influxdb3.WriteOption)) *MockClient_WritePoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*influxdb3.Point
		if args[1] != nil {
			arg1 = args[1].([]*influxdb3.Point)
		}
		var arg2 []influxdb3.WriteOption
		variadicArgs := make([]influxdb3.WriteOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(influxdb3.WriteOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_WritePoints_Call) Return(err error) *MockClient_WritePoints_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_WritePoints_Call) RunAndReturn(run func(ctx context.Context, points []*influxdb3.Point, opts ...influxdb3.WriteOption) error) *MockClient_WritePoints_Call {
	_c.Call.Return(run)
	return _c
}
