// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mqtt "github.com/dombyte/datalogger/internal/output/mqtt"
	mock "github.com/stretchr/testify/mock"
)

// Dialer is an autogenerated mock type for the Dialer type
type Dialer struct {
	mock.Mock
}

type Dialer_Expecter struct {
	mock *mock.Mock
}

func (_m *Dialer) EXPECT() *Dialer_Expecter {
	return &Dialer_Expecter{mock: &_m.Mock}
}

// Dial provides a mock function with given fields: ctx
func (_m *Dialer) Dial(ctx context.Context) (mqtt.Publisher, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Dial")
	}

	var r0 mqtt.Publisher
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (mqtt.Publisher, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) mqtt.Publisher); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mqtt.Publisher)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Dialer_Dial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dial'
type Dialer_Dial_Call struct {
	*mock.Call
}

// Dial is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Dialer_Expecter) Dial(ctx interface{}) *Dialer_Dial_Call {
	return &Dialer_Dial_Call{Call: _e.mock.On("Dial", ctx)}
}

func (_c *Dialer_Dial_Call) Run(run func(ctx context.Context)) *Dialer_Dial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Dialer_Dial_Call) Return(_a0 mqtt.Publisher, _a1 error) *Dialer_Dial_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Dialer_Dial_Call) RunAndReturn(run func(context.Context) (mqtt.Publisher, error)) *Dialer_Dial_Call {
	_c.Call.Return(run)
	return _c
}

// NewDialer creates a new instance of Dialer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDialer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Dialer {
	mock := &Dialer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
