// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/eclipse/paho.golang/paho"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPublisher creates a new instance of MockPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublisher {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockPublisher is an autogenerated mock type for the Publisher type
type MockPublisher struct {
	mock.Mock
}

type MockPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublisher) EXPECT() *MockPublisher_Expecter {
	return &MockPublisher_Expecter{mock: &_m.Mock}
}

// Disconnect provides a mock function for the type MockPublisher
func (_mock *MockPublisher) Disconnect(d *paho.Disconnect) error {
	ret := _mock.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*paho.Disconnect) error); ok {
		r0 = returnFunc(d)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPublisher_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type MockPublisher_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
//   - d *paho.Disconnect
func (_e *MockPublisher_Expecter) Disconnect(d any) *MockPublisher_Disconnect_Call {
	return &MockPublisher_Disconnect_Call{Call: _e.mock.On("Disconnect", d)}
}

func (_c *MockPublisher_Disconnect_Call) Run(run func(d *paho.Disconnect)) *MockPublisher_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *paho.Disconnect
		if args[0] != nil {
			arg0 = args[0].(*paho.Disconnect)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPublisher_Disconnect_Call) Return(err error) *MockPublisher_Disconnect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPublisher_Disconnect_Call) RunAndReturn(run func(d *paho.Disconnect) error) *MockPublisher_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// Done provides a mock function for the type MockPublisher
func (_mock *MockPublisher) Done() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// MockPublisher_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MockPublisher_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *MockPublisher_Expecter) Done() *MockPublisher_Done_Call {
	return &MockPublisher_Done_Call{Call: _e.mock.On("Done")}
}

func (_c *MockPublisher_Done_Call) Run(run func()) *MockPublisher_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPublisher_Done_Call) Return(valCh <-chan struct{}) *MockPublisher_Done_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MockPublisher_Done_Call) RunAndReturn(run func() <-chan struct{}) *MockPublisher_Done_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type MockPublisher
func (_mock *MockPublisher) Publish(ctx context.Context, p *paho.Publish) (*paho.PublishResponse, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 *paho.PublishResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *paho.Publish) (*paho.PublishResponse, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *paho.Publish) *paho.PublishResponse); ok {
		r0 = returnFunc(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paho.PublishResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *paho.Publish) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - p *paho.Publish
func (_e *MockPublisher_Expecter) Publish(ctx any, p any) *MockPublisher_Publish_Call {
	return &MockPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, p)}
}

func (_c *MockPublisher_Publish_Call) Run(run func(ctx context.Context, p *paho.Publish)) *MockPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *paho.Publish
		if args[1] != nil {
			arg1 = args[1].(*paho.Publish)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPublisher_Publish_Call) Return(publishResponse *paho.PublishResponse, err error) *MockPublisher_Publish_Call {
	_c.Call.Return(publishResponse, err)
	return _c
}

func (_c *MockPublisher_Publish_Call) RunAndReturn(run func(ctx context.Context, p *paho.Publish) (*paho.PublishResponse, error)) *MockPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}
