// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	paho "github.com/eclipse/paho.golang/paho"
)

// Publisher is an autogenerated mock type for the Publisher type
type Publisher struct {
	mock.Mock
}

type Publisher_Expecter struct {
	mock *mock.Mock
}

func (_m *Publisher) EXPECT() *Publisher_Expecter {
	return &Publisher_Expecter{mock: &_m.Mock}
}

// Disconnect provides a mock function with given fields: d
func (_m *Publisher) Disconnect(d *paho.Disconnect) error {
	ret := _m.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*paho.Disconnect) error); ok {
		r0 = rf(d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Publisher_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type Publisher_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
//   - d *paho.Disconnect
func (_e *Publisher_Expecter) Disconnect(d interface{}) *Publisher_Disconnect_Call {
	return &Publisher_Disconnect_Call{Call: _e.mock.On("Disconnect", d)}
}

func (_c *Publisher_Disconnect_Call) Run(run func(d *paho.Disconnect)) *Publisher_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*paho.Disconnect))
	})
	return _c
}

func (_c *Publisher_Disconnect_Call) Return(_a0 error) *Publisher_Disconnect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Publisher_Disconnect_Call) RunAndReturn(run func(*paho.Disconnect) error) *Publisher_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// Done provides a mock function with no fields
func (_m *Publisher) Done() <-chan struct{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 <-chan struct{}
	if rf, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}

	return r0
}

// Publisher_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type Publisher_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *Publisher_Expecter) Done() *Publisher_Done_Call {
	return &Publisher_Done_Call{Call: _e.mock.On("Done")}
}

func (_c *Publisher_Done_Call) Run(run func()) *Publisher_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Publisher_Done_Call) Return(_a0 <-chan struct{}) *Publisher_Done_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Publisher_Done_Call) RunAndReturn(run func() <-chan struct{}) *Publisher_Done_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function with given fields: ctx, p
func (_m *Publisher) Publish(ctx context.Context, p *paho.Publish) (*paho.PublishResponse, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 *paho.PublishResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *paho.Publish) (*paho.PublishResponse, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *paho.Publish) *paho.PublishResponse); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paho.PublishResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *paho.Publish) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Publisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type Publisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - p *paho.Publish
func (_e *Publisher_Expecter) Publish(ctx interface{}, p interface{}) *Publisher_Publish_Call {
	return &Publisher_Publish_Call{Call: _e.mock.On("Publish", ctx, p)}
}

func (_c *Publisher_Publish_Call) Run(run func(ctx context.Context, p *paho.Publish)) *Publisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*paho.Publish))
	})
	return _c
}

func (_c *Publisher_Publish_Call) Return(_a0 *paho.PublishResponse, _a1 error) *Publisher_Publish_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Publisher_Publish_Call) RunAndReturn(run func(context.Context, *paho.Publish) (*paho.PublishResponse, error)) *Publisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewPublisher creates a new instance of Publisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Publisher {
	mock := &Publisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
