// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	simonvettermodbus "github.com/simonvetter/modbus"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *Client) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Client_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Client_Expecter) Close() *Client_Close_Call {
	return &Client_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Client_Close_Call) Run(run func()) *Client_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Close_Call) Return(_a0 error) *Client_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_Close_Call) RunAndReturn(run func() error) *Client_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ReadRegisters provides a mock function with given fields: addr, quantity, regType
func (_m *Client) ReadRegisters(addr uint16, quantity uint16, regType simonvettermodbus.RegType) ([]uint16, error) {
	ret := _m.Called(addr, quantity, regType)

	if len(ret) == 0 {
		panic("no return value specified for ReadRegisters")
	}

	var r0 []uint16
	var r1 error
	if rf, ok := ret.Get(0).(func(uint16, uint16, simonvettermodbus.RegType) ([]uint16, error)); ok {
		return rf(addr, quantity, regType)
	}
	if rf, ok := ret.Get(0).(func(uint16, uint16, simonvettermodbus.RegType) []uint16); ok {
		r0 = rf(addr, quantity, regType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint16)
		}
	}

	if rf, ok := ret.Get(1).(func(uint16, uint16, simonvettermodbus.RegType) error); ok {
		r1 = rf(addr, quantity, regType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ReadRegisters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadRegisters'
type Client_ReadRegisters_Call struct {
	*mock.Call
}

// ReadRegisters is a helper method to define mock.On call
//   - addr uint16
//   - quantity uint16
//   - regType simonvettermodbus.RegType
func (_e *Client_Expecter) ReadRegisters(addr interface{}, quantity interface{}, regType interface{}) *Client_ReadRegisters_Call {
	return &Client_ReadRegisters_Call{Call: _e.mock.On("ReadRegisters", addr, quantity, regType)}
}

func (_c *Client_ReadRegisters_Call) Run(run func(addr uint16, quantity uint16, regType simonvettermodbus.RegType)) *Client_ReadRegisters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint16), args[1].(uint16), args[2].(simonvettermodbus.RegType))
	})
	return _c
}

func (_c *Client_ReadRegisters_Call) Return(_a0 []uint16, _a1 error) *Client_ReadRegisters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_ReadRegisters_Call) RunAndReturn(run func(uint16, uint16, simonvettermodbus.RegType) ([]uint16, error)) *Client_ReadRegisters_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
