// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	modbus "github.com/dombyte/datalogger/internal/datasource/modbus"
	mock "github.com/stretchr/testify/mock"
)

// Dialer is an autogenerated mock type for the Dialer type
type Dialer struct {
	mock.Mock
}

type Dialer_Expecter struct {
	mock *mock.Mock
}

func (_m *Dialer) EXPECT() *Dialer_Expecter {
	return &Dialer_Expecter{mock: &_m.Mock}
}

// Dial provides a mock function with no fields
func (_m *Dialer) Dial() (modbus.Client, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dial")
	}

	var r0 modbus.Client
	var r1 error
	if rf, ok := ret.Get(0).(func() (modbus.Client, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() modbus.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(modbus.Client)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Dialer_Dial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dial'
type Dialer_Dial_Call struct {
	*mock.Call
}

// Dial is a helper method to define mock.On call
func (_e *Dialer_Expecter) Dial() *Dialer_Dial_Call {
	return &Dialer_Dial_Call{Call: _e.mock.On("Dial")}
}

func (_c *Dialer_Dial_Call) Run(run func()) *Dialer_Dial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Dialer_Dial_Call) Return(_a0 modbus.Client, _a1 error) *Dialer_Dial_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Dialer_Dial_Call) RunAndReturn(run func() (modbus.Client, error)) *Dialer_Dial_Call {
	_c.Call.Return(run)
	return _c
}

// NewDialer creates a new instance of Dialer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDialer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Dialer {
	mock := &Dialer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
