// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/simonvetter/modbus"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockClient
func (_mock *MockClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(err error) *MockClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ReadRegisters provides a mock function for the type MockClient
func (_mock *MockClient) ReadRegisters(addr uint16, quantity uint16, regType modbus.RegType) ([]uint16, error) {
	ret := _mock.Called(addr, quantity, regType)

	if len(ret) == 0 {
		panic("no return value specified for ReadRegisters")
	}

	var r0 []uint16
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint16, uint16, modbus.RegType) ([]uint16, error)); ok {
		return returnFunc(addr, quantity, regType)
	}
	if returnFunc, ok := ret.Get(0).(func(uint16, uint16, modbus.RegType) []uint16); ok {
		r0 = returnFunc(addr, quantity, regType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint16)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint16, uint16, modbus.RegType) error); ok {
		r1 = returnFunc(addr, quantity, regType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ReadRegisters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadRegisters'
type MockClient_ReadRegisters_Call struct {
	*mock.Call
}

// ReadRegisters is a helper method to define mock.On call
//   - addr uint16
//   - quantity uint16
//   - regType modbus.RegType
func (_e *MockClient_Expecter) ReadRegisters(addr any, quantity any, regType any) *MockClient_ReadRegisters_Call {
	return &MockClient_ReadRegisters_Call{Call: _e.mock.On("ReadRegisters", addr, quantity, regType)}
}

func (_c *MockClient_ReadRegisters_Call) Run(run func(addr uint16, quantity uint16, regType modbus.RegType)) *MockClient_ReadRegisters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint16
		if args[0] != nil {
			arg0 = args[0].(uint16)
		}
		var arg1 uint16
		if args[1] != nil {
			arg1 = args[1].(uint16)
		}
		var arg2 modbus.RegType
		if args[2] != nil {
			arg2 = args[2].(modbus.RegType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ReadRegisters_Call) Return(uint16s []uint16, err error) *MockClient_ReadRegisters_Call {
	_c.Call.Return(uint16s, err)
	return _c
}

func (_c *MockClient_ReadRegisters_Call) RunAndReturn(run func(addr uint16, quantity uint16, regType modbus.RegType) ([]uint16, error)) *MockClient_ReadRegisters_Call {
	_c.Call.Return(run)
	return _c
}
